---

- name: conf.d
  template:
    src: "{{ item }}.j2"
    dest: "/etc/httpd/conf.d/{{ item }}"
    owner: root
    group: root
    mode: 0644
  with_items: "{{httpd_confd}}"
  notify: svc restart httpd

- name: conf.d gists
  get_url:
    url: "https://gist.githubusercontent.com/{{ item.gist }}/raw"
    dest: "/etc/httpd/conf.d/{{ item.dest }}"
    owner: root
    group: root
    mode: 0644
  with_items: "{{httpd_confd_gists}}"
  notify: svc restart httpd

- name: conf.d reverse-proxy.conf
  template:
    src: "reverse-proxy.conf.j2"
    dest: "/etc/httpd/conf.d/reverse-proxy.conf"
    owner: root
    group: root
    mode: 0644
  when: httpd_conf_reverseproxy
  notify: svc restart httpd

- name: conf.d ssl.conf
  template:
    src: "{{ansible_os_family}}-{{ansible_distribution_major_version}}-ssl.conf.j2"
    dest: "/etc/httpd/conf.d/ssl.conf"
    owner: root
    group: root
    mode: 0644
  notify: svc restart httpd
  when: httpd_ssl is defined and httpd_ssl

- name: conf.d authz_ldap.conf
  template:
    src: "{{ansible_os_family}}-{{ansible_distribution_major_version}}-authz_ldap.conf.j2"
    dest: "/etc/httpd/conf.d/authz_ldap.conf"
    owner: root
    group: root
    mode: 0644
  notify: svc restart httpd
  when: httpd_authz_ldap is defined and httpd_authz_ldap

- name: certificate content
  copy:
    content: "{{item.content}}"
    dest: "/etc/pki/tls/{{item.type}}/{{item.filename}}"
    owner: "{{item.owner|default(httpd_user)}}"
    group: "{{item.group|default(httpd_group)}}"
    mode: "{{item.mode|default(httpd_ssl_mode)}}"
  with_items: "{{httpd_ssl_certs}}"
  when: item.type is defined and item.filename is defined and item.content is defined and item.src is not defined
  notify: svc restart httpd

- name: certificate file
  copy:
    src: "{{item.file}}"
    dest: "/etc/pki/tls/{{item.type}}/{{item.filename}}"
    owner: "{{item.owner|default(httpd_user)}}"
    group: "{{item.group|default(httpd_group)}}"
    mode: "{{item.mode|default(httpd_ssl_mode)}}"
  with_items: "{{httpd_ssl_certs}}"
  when: item.type is defined and item.filename is defined and item.file is defined and item.content is not defined
  notify: svc restart httpd

- name: blank index.html in web root
  file: dest=/var/www/html/index.html state=touch
  when: httpd_blank_webroot_index

- name: service enable, start
  service:
    name={{httpd_pkg_name}}
    state={{httpd_svc_state}}
    enabled={{httpd_svc_enabled}}

