---

- name: install pkg
  yum:
    name: "{{item}}"
    state: installed
  with_items:
    - httpd
    - mod_ssl

- name: service enable, start
  service:
    name: httpd
    state: started
    enabled: yes

