---

- name: install pkg
  yum:
    name={{httpd_pkg_name}}
    state={{httpd_pkg_state}}

- name: install mod_ssl
  yum:
    name=mod_ssl
    state={{httpd_pkg_state}}
  when: httpd_ssl is defined and httpd_ssl

- name: install mod_authz_ldap
  yum:
    name=mod_authz_ldap
    state={{httpd_pkg_state}}
  when: httpd_authz_ldap is defined and httpd_authz_ldap
