---

- name: install pkg
  yum:
    name={{item}}
    state={{httpd_pkg_state}}
  with_items:
    - httpd

- name: install mod_ssl
  yum:
    name=mod_ssl
    state={{httpd_pkg_state}}
  when: httpd_ssl is defined and httpd_ssl

